// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: iam/v1/secret_runtime.proto

package secretpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSecretCandidatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Families      []string               `protobuf:"bytes,1,rep,name=families,proto3" json:"families,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretCandidatesRequest) Reset() {
	*x = GetSecretCandidatesRequest{}
	mi := &file_iam_v1_secret_runtime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretCandidatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretCandidatesRequest) ProtoMessage() {}

func (x *GetSecretCandidatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_v1_secret_runtime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretCandidatesRequest.ProtoReflect.Descriptor instead.
func (*GetSecretCandidatesRequest) Descriptor() ([]byte, []int) {
	return file_iam_v1_secret_runtime_proto_rawDescGZIP(), []int{0}
}

func (x *GetSecretCandidatesRequest) GetFamilies() []string {
	if x != nil {
		return x.Families
	}
	return nil
}

type GetSecretCandidatesResponse struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Families      map[string]*SecretVersionList `protobuf:"bytes,1,rep,name=families,proto3" json:"families,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretCandidatesResponse) Reset() {
	*x = GetSecretCandidatesResponse{}
	mi := &file_iam_v1_secret_runtime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretCandidatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretCandidatesResponse) ProtoMessage() {}

func (x *GetSecretCandidatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iam_v1_secret_runtime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretCandidatesResponse.ProtoReflect.Descriptor instead.
func (*GetSecretCandidatesResponse) Descriptor() ([]byte, []int) {
	return file_iam_v1_secret_runtime_proto_rawDescGZIP(), []int{1}
}

func (x *GetSecretCandidatesResponse) GetFamilies() map[string]*SecretVersionList {
	if x != nil {
		return x.Families
	}
	return nil
}

type SecretVersionList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Candidates    []*SecretVersion       `protobuf:"bytes,1,rep,name=candidates,proto3" json:"candidates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretVersionList) Reset() {
	*x = SecretVersionList{}
	mi := &file_iam_v1_secret_runtime_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretVersionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretVersionList) ProtoMessage() {}

func (x *SecretVersionList) ProtoReflect() protoreflect.Message {
	mi := &file_iam_v1_secret_runtime_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretVersionList.ProtoReflect.Descriptor instead.
func (*SecretVersionList) Descriptor() ([]byte, []int) {
	return file_iam_v1_secret_runtime_proto_rawDescGZIP(), []int{2}
}

func (x *SecretVersionList) GetCandidates() []*SecretVersion {
	if x != nil {
		return x.Candidates
	}
	return nil
}

type SecretVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Family        string                 `protobuf:"bytes,1,opt,name=family,proto3" json:"family,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	RotatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=rotated_at,json=rotatedAt,proto3" json:"rotated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretVersion) Reset() {
	*x = SecretVersion{}
	mi := &file_iam_v1_secret_runtime_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretVersion) ProtoMessage() {}

func (x *SecretVersion) ProtoReflect() protoreflect.Message {
	mi := &file_iam_v1_secret_runtime_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretVersion.ProtoReflect.Descriptor instead.
func (*SecretVersion) Descriptor() ([]byte, []int) {
	return file_iam_v1_secret_runtime_proto_rawDescGZIP(), []int{3}
}

func (x *SecretVersion) GetFamily() string {
	if x != nil {
		return x.Family
	}
	return ""
}

func (x *SecretVersion) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *SecretVersion) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SecretVersion) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *SecretVersion) GetRotatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RotatedAt
	}
	return nil
}

var File_iam_v1_secret_runtime_proto protoreflect.FileDescriptor

const file_iam_v1_secret_runtime_proto_rawDesc = "" +
	"\n" +
	"\x1biam/v1/secret_runtime.proto\x12\raurora.iam.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"8\n" +
	"\x1aGetSecretCandidatesRequest\x12\x1a\n" +
	"\bfamilies\x18\x01 \x03(\tR\bfamilies\"\xd2\x01\n" +
	"\x1bGetSecretCandidatesResponse\x12T\n" +
	"\bfamilies\x18\x01 \x03(\v28.aurora.iam.v1.GetSecretCandidatesResponse.FamiliesEntryR\bfamilies\x1a]\n" +
	"\rFamiliesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x126\n" +
	"\x05value\x18\x02 \x01(\v2 .aurora.iam.v1.SecretVersionListR\x05value:\x028\x01\"Q\n" +
	"\x11SecretVersionList\x12<\n" +
	"\n" +
	"candidates\x18\x01 \x03(\v2\x1c.aurora.iam.v1.SecretVersionR\n" +
	"candidates\"\xcd\x01\n" +
	"\rSecretVersion\x12\x16\n" +
	"\x06family\x18\x01 \x01(\tR\x06family\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x129\n" +
	"\n" +
	"rotated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\trotatedAt2\x84\x01\n" +
	"\x14SecretRuntimeService\x12l\n" +
	"\x13GetSecretCandidates\x12).aurora.iam.v1.GetSecretCandidatesRequest\x1a*.aurora.iam.v1.GetSecretCandidatesResponseB/Z-iam/internal/transport/grpc/secretpb;secretpbb\x06proto3"

var (
	file_iam_v1_secret_runtime_proto_rawDescOnce sync.Once
	file_iam_v1_secret_runtime_proto_rawDescData []byte
)

func file_iam_v1_secret_runtime_proto_rawDescGZIP() []byte {
	file_iam_v1_secret_runtime_proto_rawDescOnce.Do(func() {
		file_iam_v1_secret_runtime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_iam_v1_secret_runtime_proto_rawDesc), len(file_iam_v1_secret_runtime_proto_rawDesc)))
	})
	return file_iam_v1_secret_runtime_proto_rawDescData
}

var file_iam_v1_secret_runtime_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_iam_v1_secret_runtime_proto_goTypes = []any{
	(*GetSecretCandidatesRequest)(nil),  // 0: aurora.iam.v1.GetSecretCandidatesRequest
	(*GetSecretCandidatesResponse)(nil), // 1: aurora.iam.v1.GetSecretCandidatesResponse
	(*SecretVersionList)(nil),           // 2: aurora.iam.v1.SecretVersionList
	(*SecretVersion)(nil),               // 3: aurora.iam.v1.SecretVersion
	nil,                                 // 4: aurora.iam.v1.GetSecretCandidatesResponse.FamiliesEntry
	(*timestamppb.Timestamp)(nil),       // 5: google.protobuf.Timestamp
}
var file_iam_v1_secret_runtime_proto_depIdxs = []int32{
	4, // 0: aurora.iam.v1.GetSecretCandidatesResponse.families:type_name -> aurora.iam.v1.GetSecretCandidatesResponse.FamiliesEntry
	3, // 1: aurora.iam.v1.SecretVersionList.candidates:type_name -> aurora.iam.v1.SecretVersion
	5, // 2: aurora.iam.v1.SecretVersion.expires_at:type_name -> google.protobuf.Timestamp
	5, // 3: aurora.iam.v1.SecretVersion.rotated_at:type_name -> google.protobuf.Timestamp
	2, // 4: aurora.iam.v1.GetSecretCandidatesResponse.FamiliesEntry.value:type_name -> aurora.iam.v1.SecretVersionList
	0, // 5: aurora.iam.v1.SecretRuntimeService.GetSecretCandidates:input_type -> aurora.iam.v1.GetSecretCandidatesRequest
	1, // 6: aurora.iam.v1.SecretRuntimeService.GetSecretCandidates:output_type -> aurora.iam.v1.GetSecretCandidatesResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_iam_v1_secret_runtime_proto_init() }
func file_iam_v1_secret_runtime_proto_init() {
	if File_iam_v1_secret_runtime_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_iam_v1_secret_runtime_proto_rawDesc), len(file_iam_v1_secret_runtime_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_iam_v1_secret_runtime_proto_goTypes,
		DependencyIndexes: file_iam_v1_secret_runtime_proto_depIdxs,
		MessageInfos:      file_iam_v1_secret_runtime_proto_msgTypes,
	}.Build()
	File_iam_v1_secret_runtime_proto = out.File
	file_iam_v1_secret_runtime_proto_goTypes = nil
	file_iam_v1_secret_runtime_proto_depIdxs = nil
}
