// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: iam/v1/admin_session.proto

package adminsessionpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdminSessionService_AuthorizeSession_FullMethodName = "/aurora.iam.v1.AdminSessionService/AuthorizeSession"
)

// AdminSessionServiceClient is the client API for AdminSessionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminSessionServiceClient interface {
	AuthorizeSession(ctx context.Context, in *AuthorizeAdminSessionRequest, opts ...grpc.CallOption) (*AuthorizeAdminSessionResponse, error)
}

type adminSessionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminSessionServiceClient(cc grpc.ClientConnInterface) AdminSessionServiceClient {
	return &adminSessionServiceClient{cc}
}

func (c *adminSessionServiceClient) AuthorizeSession(ctx context.Context, in *AuthorizeAdminSessionRequest, opts ...grpc.CallOption) (*AuthorizeAdminSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthorizeAdminSessionResponse)
	err := c.cc.Invoke(ctx, AdminSessionService_AuthorizeSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminSessionServiceServer is the server API for AdminSessionService service.
// All implementations must embed UnimplementedAdminSessionServiceServer
// for forward compatibility.
type AdminSessionServiceServer interface {
	AuthorizeSession(context.Context, *AuthorizeAdminSessionRequest) (*AuthorizeAdminSessionResponse, error)
	mustEmbedUnimplementedAdminSessionServiceServer()
}

// UnimplementedAdminSessionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminSessionServiceServer struct{}

func (UnimplementedAdminSessionServiceServer) AuthorizeSession(context.Context, *AuthorizeAdminSessionRequest) (*AuthorizeAdminSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthorizeSession not implemented")
}
func (UnimplementedAdminSessionServiceServer) mustEmbedUnimplementedAdminSessionServiceServer() {}
func (UnimplementedAdminSessionServiceServer) testEmbeddedByValue()                             {}

// UnsafeAdminSessionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminSessionServiceServer will
// result in compilation errors.
type UnsafeAdminSessionServiceServer interface {
	mustEmbedUnimplementedAdminSessionServiceServer()
}

func RegisterAdminSessionServiceServer(s grpc.ServiceRegistrar, srv AdminSessionServiceServer) {
	// If the following call pancis, it indicates UnimplementedAdminSessionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminSessionService_ServiceDesc, srv)
}

func _AdminSessionService_AuthorizeSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorizeAdminSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminSessionServiceServer).AuthorizeSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminSessionService_AuthorizeSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminSessionServiceServer).AuthorizeSession(ctx, req.(*AuthorizeAdminSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminSessionService_ServiceDesc is the grpc.ServiceDesc for AdminSessionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminSessionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aurora.iam.v1.AdminSessionService",
	HandlerType: (*AdminSessionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AuthorizeSession",
			Handler:    _AdminSessionService_AuthorizeSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "iam/v1/admin_session.proto",
}
