// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: iam/v1/admin_session.proto

package adminsessionpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthorizeAdminSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionToken  string                 `protobuf:"bytes,1,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	DeviceSecret  string                 `protobuf:"bytes,3,opt,name=device_secret,json=deviceSecret,proto3" json:"device_secret,omitempty"`
	ClientIp      string                 `protobuf:"bytes,4,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	UserAgent     string                 `protobuf:"bytes,5,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeAdminSessionRequest) Reset() {
	*x = AuthorizeAdminSessionRequest{}
	mi := &file_iam_v1_admin_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeAdminSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeAdminSessionRequest) ProtoMessage() {}

func (x *AuthorizeAdminSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_v1_admin_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeAdminSessionRequest.ProtoReflect.Descriptor instead.
func (*AuthorizeAdminSessionRequest) Descriptor() ([]byte, []int) {
	return file_iam_v1_admin_session_proto_rawDescGZIP(), []int{0}
}

func (x *AuthorizeAdminSessionRequest) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *AuthorizeAdminSessionRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *AuthorizeAdminSessionRequest) GetDeviceSecret() string {
	if x != nil {
		return x.DeviceSecret
	}
	return ""
}

func (x *AuthorizeAdminSessionRequest) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *AuthorizeAdminSessionRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

type AuthorizeAdminSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdminUserId   string                 `protobuf:"bytes,1,opt,name=admin_user_id,json=adminUserId,proto3" json:"admin_user_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	CredentialId  string                 `protobuf:"bytes,3,opt,name=credential_id,json=credentialId,proto3" json:"credential_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,4,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeAdminSessionResponse) Reset() {
	*x = AuthorizeAdminSessionResponse{}
	mi := &file_iam_v1_admin_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeAdminSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeAdminSessionResponse) ProtoMessage() {}

func (x *AuthorizeAdminSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iam_v1_admin_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeAdminSessionResponse.ProtoReflect.Descriptor instead.
func (*AuthorizeAdminSessionResponse) Descriptor() ([]byte, []int) {
	return file_iam_v1_admin_session_proto_rawDescGZIP(), []int{1}
}

func (x *AuthorizeAdminSessionResponse) GetAdminUserId() string {
	if x != nil {
		return x.AdminUserId
	}
	return ""
}

func (x *AuthorizeAdminSessionResponse) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *AuthorizeAdminSessionResponse) GetCredentialId() string {
	if x != nil {
		return x.CredentialId
	}
	return ""
}

func (x *AuthorizeAdminSessionResponse) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *AuthorizeAdminSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

var File_iam_v1_admin_session_proto protoreflect.FileDescriptor

const file_iam_v1_admin_session_proto_rawDesc = "" +
	"\n" +
	"\x1aiam/v1/admin_session.proto\x12\raurora.iam.v1\"\xc1\x01\n" +
	"\x1cAuthorizeAdminSessionRequest\x12#\n" +
	"\rsession_token\x18\x01 \x01(\tR\fsessionToken\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12#\n" +
	"\rdevice_secret\x18\x03 \x01(\tR\fdeviceSecret\x12\x1b\n" +
	"\tclient_ip\x18\x04 \x01(\tR\bclientIp\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x05 \x01(\tR\tuserAgent\"\xc7\x01\n" +
	"\x1dAuthorizeAdminSessionResponse\x12\"\n" +
	"\radmin_user_id\x18\x01 \x01(\tR\vadminUserId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12#\n" +
	"\rcredential_id\x18\x03 \x01(\tR\fcredentialId\x12\x1b\n" +
	"\tdevice_id\x18\x04 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x05 \x01(\tR\tsessionId2\x84\x01\n" +
	"\x13AdminSessionService\x12m\n" +
	"\x10AuthorizeSession\x12+.aurora.iam.v1.AuthorizeAdminSessionRequest\x1a,.aurora.iam.v1.AuthorizeAdminSessionResponseB;Z9iam/internal/transport/grpc/adminsessionpb;adminsessionpbb\x06proto3"

var (
	file_iam_v1_admin_session_proto_rawDescOnce sync.Once
	file_iam_v1_admin_session_proto_rawDescData []byte
)

func file_iam_v1_admin_session_proto_rawDescGZIP() []byte {
	file_iam_v1_admin_session_proto_rawDescOnce.Do(func() {
		file_iam_v1_admin_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_iam_v1_admin_session_proto_rawDesc), len(file_iam_v1_admin_session_proto_rawDesc)))
	})
	return file_iam_v1_admin_session_proto_rawDescData
}

var file_iam_v1_admin_session_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_iam_v1_admin_session_proto_goTypes = []any{
	(*AuthorizeAdminSessionRequest)(nil),  // 0: aurora.iam.v1.AuthorizeAdminSessionRequest
	(*AuthorizeAdminSessionResponse)(nil), // 1: aurora.iam.v1.AuthorizeAdminSessionResponse
}
var file_iam_v1_admin_session_proto_depIdxs = []int32{
	0, // 0: aurora.iam.v1.AdminSessionService.AuthorizeSession:input_type -> aurora.iam.v1.AuthorizeAdminSessionRequest
	1, // 1: aurora.iam.v1.AdminSessionService.AuthorizeSession:output_type -> aurora.iam.v1.AuthorizeAdminSessionResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_iam_v1_admin_session_proto_init() }
func file_iam_v1_admin_session_proto_init() {
	if File_iam_v1_admin_session_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_iam_v1_admin_session_proto_rawDesc), len(file_iam_v1_admin_session_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_iam_v1_admin_session_proto_goTypes,
		DependencyIndexes: file_iam_v1_admin_session_proto_depIdxs,
		MessageInfos:      file_iam_v1_admin_session_proto_msgTypes,
	}.Build()
	File_iam_v1_admin_session_proto = out.File
	file_iam_v1_admin_session_proto_goTypes = nil
	file_iam_v1_admin_session_proto_depIdxs = nil
}
